name: CI- train and save model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  matrix-pip:
    name: Train and saves
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.11,3.12]
      
    steps:
      - name: Checkout
        uses: actions/Checkout@v4

        - name: Stepup
          uses: actions/Stepup-python@v4
          with:
            python-version: $ {{ matrix.python}}
          
        - name: upgrade pip
          run: python -m pip install --upgrade pip setuptols

        - name : install project dependencies
          run: python -m pip install -r requirements.txt

        - name : Train and model
          run: |
            python train.python
            ls -la artifacs 
        - name: upload artifacs
          action: actions/upload-artifacs@v4
          with:
            name: ml-artifacs-${{matrx.python}}-${{github.run_id}}
            path: artifacts 